name: Check

on:
    push:
        branches: [main]
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: samueldr/lix-gha-installer-action@v2026-02-22

            - name: Assert Lix runtime
              run: |
                  nix --version
                  nix --version | grep -q "Lix"

            - name: Evaluate darwin configuration
              run: nix eval .#darwinConfigurations.trfmbp.system --raw

            - name: Evaluate nixos configurations
              run: |
                  nix eval .#nixosConfigurations.trfnix.config.system.build.toplevel.drvPath --raw
                  nix eval .#nixosConfigurations.trfwsl.config.system.build.toplevel.drvPath --raw

            - name: Check formatting
              run: nix build .#checks.x86_64-linux.formatting --no-link
